# site settings
title: Lenia Musix
subtitle: Gesang, Band und Musik
email:
description: Vorstellung meiner Passion, Angebote und Projekte 
baseurl: "/homepage" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address:
city:
state:
zip_code:
country: Deutschland
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub:
  GitLab:
  Google-Plus:
  Tiktok: "https://www.tiktok.com/@lenia.musix"
  Instagram: "https://www.instagram.com/lenia_x8"
  LinkedIn:
  Twitter:
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed
  load_paths:
    - assets/fontawesome/css

# Ensure these directories are included in the build
include:
  - assets/css
  - assets/webfonts

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
- elements.md
- all_posts.md
- generic.md
- landing.md
